version: '3'

services:
  db:
    image: postgres
    tty: true 
  web:
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    #command: bash
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true 