version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    #command: python3 manage.py makemigrations Amazon
    #command: python3 manage.py makemigrations Images
    #command: python3 manage.py migrate
    #command: bash
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true 